apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  creationTimestamp: null
  labels:
    service: jenkins
  name: jenkins
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  - name: "443"
    port: 443
    targetPort: 8443
  - name: "50000"
    port: 50000
    targetPort: 50000
  selector:
    service: jenkins
  type: LoadBalancer
