kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dd-managed-hdd-15g
  annotations:
    volume.beta.kubernetes.io/storage-class: managedhdd0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
