kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dd-managed-hdd-8g
  annotations:
    volume.beta.kubernetes.io/storage-class: managedhdd1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
